# Generated by Django 3.0.3 on 2020-05-11 07:23

from django.db import migrations, models
import paste_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.CharField(default=paste_app.models.hex_uuid, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
        ),
    ]
